-- Generated from specs/shaman/enhancement/catalog.json; do not edit.
local _, Spynon = ...

local Catalog = {
  ["actions"] = {
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          114051,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.ascendance",
      ["kind"] = "spell",
      ["label"] = "Ascendance",
      ["spellId"] = 114051,
      ["tags"] = {
        "cooldown",
        "melee",
        "transformation",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          188443,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.chain_lightning",
      ["kind"] = "spell",
      ["label"] = "Chain Lightning",
      ["spellId"] = 188443,
      ["tags"] = {
        "aoe",
        "damage",
        "maelstrom_spender",
        "nature",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          187874,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.crash_lightning",
      ["kind"] = "spell",
      ["label"] = "Crash Lightning",
      ["spellId"] = 187874,
      ["tags"] = {
        "aoe",
        "damage",
        "melee",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          384352,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.doom_winds",
      ["kind"] = "spell",
      ["label"] = "Doom Winds",
      ["spellId"] = 384352,
      ["tags"] = {
        "cooldown",
        "damage",
        "melee",
      },
    },
    {
      ["availability"] = {
        ["forbiddenTalentSpellIds"] = {
          470057,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.flame_shock",
      ["kind"] = "spell",
      ["label"] = "Flame Shock",
      ["spellId"] = 470411,
      ["tags"] = {
        "damage",
        "fire",
        "ranged",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          318038,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.flametongue_weapon",
      ["kind"] = "spell",
      ["label"] = "Flametongue Weapon",
      ["spellId"] = 318038,
      ["tags"] = {
        "imbue",
        "maintenance",
        "self_buff",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          196840,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.frost_shock",
      ["kind"] = "spell",
      ["label"] = "Frost Shock",
      ["spellId"] = 196840,
      ["tags"] = {
        "damage",
        "frost",
        "ranged",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          60103,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.lava_lash",
      ["kind"] = "spell",
      ["label"] = "Lava Lash",
      ["spellId"] = 60103,
      ["tags"] = {
        "damage",
        "fire",
        "melee",
      },
    },
    {
      ["availability"] = {},
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.lightning_bolt",
      ["kind"] = "spell",
      ["label"] = "Lightning Bolt",
      ["spellId"] = 188196,
      ["tags"] = {
        "damage",
        "maelstrom_spender",
        "nature",
        "ranged",
      },
    },
    {
      ["availability"] = {},
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.lightning_shield",
      ["kind"] = "spell",
      ["label"] = "Lightning Shield",
      ["spellId"] = 192106,
      ["tags"] = {
        "maintenance",
        "self_buff",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          1218047,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.primordial_storm",
      ["kind"] = "spell",
      ["label"] = "Primordial Storm",
      ["spellId"] = 1218090,
      ["tags"] = {
        "aoe",
        "damage",
        "maelstrom_spender",
        "replacement",
      },
    },
    {
      ["availability"] = {},
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.stormstrike",
      ["kind"] = "spell",
      ["label"] = "Stormstrike",
      ["spellId"] = 17364,
      ["tags"] = {
        "damage",
        "melee",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          197214,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.sundering",
      ["kind"] = "spell",
      ["label"] = "Sundering",
      ["spellId"] = 197214,
      ["tags"] = {
        "aoe",
        "damage",
        "melee",
      },
    },
    {
      ["availability"] = {
        ["heroTreeId"] = "enhancement.totemic",
        ["requiredTalentSpellIds"] = {
          455630,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.surging_totem",
      ["kind"] = "spell",
      ["label"] = "Surging Totem",
      ["spellId"] = 444995,
      ["tags"] = {
        "aoe",
        "cooldown",
        "damage",
        "totem",
      },
    },
    {
      ["availability"] = {
        ["heroTreeId"] = "enhancement.stormbringer",
        ["requiredTalentSpellIds"] = {
          454009,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.tempest",
      ["kind"] = "spell",
      ["label"] = "Tempest",
      ["spellId"] = 452201,
      ["tags"] = {
        "damage",
        "maelstrom_spender",
        "nature",
        "replacement",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          470057,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.voltaic_blaze",
      ["kind"] = "spell",
      ["label"] = "Voltaic Blaze",
      ["spellId"] = 470057,
      ["tags"] = {
        "damage",
        "fire",
        "nature",
        "replacement",
      },
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          33757,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.windfury_weapon",
      ["kind"] = "spell",
      ["label"] = "Windfury Weapon",
      ["spellId"] = 33757,
      ["tags"] = {
        "imbue",
        "maintenance",
        "self_buff",
      },
    },
    {
      ["availability"] = {
        ["anyTalentSpellIds"] = {
          114051,
          378270,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.windstrike",
      ["kind"] = "spell",
      ["label"] = "Windstrike",
      ["spellId"] = 115356,
      ["tags"] = {
        "damage",
        "melee",
        "replacement",
      },
    },
  },
  ["auras"] = {
    {
      ["availability"] = {
        ["anyTalentSpellIds"] = {
          114051,
          378270,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.ascendance",
      ["label"] = "Ascendance",
      ["spellId"] = 114051,
      ["unit"] = "player",
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          390370,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.ashen_catalyst",
      ["label"] = "Ashen Catalyst",
      ["spellId"] = 390371,
      ["unit"] = "player",
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          187874,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.crash_lightning",
      ["label"] = "Crash Lightning",
      ["spellId"] = 187878,
      ["unit"] = "player",
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          384352,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.doom_winds",
      ["label"] = "Doom Winds",
      ["spellId"] = 466772,
      ["unit"] = "player",
    },
    {
      ["availability"] = {},
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.flame_shock",
      ["label"] = "Flame Shock",
      ["spellId"] = 188389,
      ["unit"] = "target",
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          201900,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.hot_hand",
      ["label"] = "Hot Hand",
      ["spellId"] = 215785,
      ["unit"] = "player",
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          334046,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.lashing_flames",
      ["label"] = "Lashing Flames",
      ["spellId"] = 334168,
      ["unit"] = "target",
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          187880,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.maelstrom_weapon",
      ["label"] = "Maelstrom Weapon",
      ["maxStacks"] = 10,
      ["spellId"] = 344179,
      ["unit"] = "player",
    },
    {
      ["availability"] = {
        ["requiredTalentSpellIds"] = {
          1218047,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.primordial_storm",
      ["label"] = "Primordial Storm",
      ["spellId"] = 1218125,
      ["unit"] = "player",
    },
    {
      ["availability"] = {
        ["heroTreeId"] = "enhancement.stormbringer",
        ["requiredTalentSpellIds"] = {
          454009,
        },
      },
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.tempest",
      ["label"] = "Tempest",
      ["spellId"] = 454015,
      ["unit"] = "player",
    },
  },
  ["classId"] = 7,
  ["displayName"] = "Enhancement Shaman",
  ["heroTrees"] = {
    {
      ["id"] = "enhancement.stormbringer",
      ["name"] = "Stormbringer",
      ["selectionEntryId"] = 123381,
      ["selectionIndex"] = 100,
      ["selectionNodeId"] = 99847,
      ["subTreeId"] = 55,
    },
    {
      ["id"] = "enhancement.totemic",
      ["name"] = "Totemic",
      ["selectionEntryId"] = 123379,
      ["selectionIndex"] = 200,
      ["selectionNodeId"] = 99847,
      ["subTreeId"] = 54,
    },
  },
  ["id"] = "shaman.enhancement",
  ["resources"] = {
    {
      ["auraId"] = 344179,
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.maelstrom_weapon",
      ["kind"] = "aura_stacks",
      ["label"] = "Maelstrom Weapon",
      ["maxStacks"] = 10,
    },
    {
      ["capability"] = "ADDON_AVAILABLE",
      ["id"] = "enhancement.mana",
      ["kind"] = "power",
      ["label"] = "Mana",
      ["powerType"] = 0,
    },
  },
  ["schemaVersion"] = 1,
  ["sources"] = {
    ["interface"] = 120100,
    ["simcEngineCommit"] = "f86979165c9b952e41d8cb6119065d3f6272abee",
    ["simcHotfixDate"] = "2026-09-01",
    ["simcVersion"] = "1210.01",
    ["wowBuild"] = 69587,
    ["wowVersion"] = "12.1.0",
  },
  ["specId"] = 263,
  ["talents"] = {
    {
      ["definitionId"] = 122483,
      ["entryId"] = 117471,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.amplification_core",
      ["maxRanks"] = 1,
      ["name"] = "Amplification Core",
      ["nodeId"] = 94874,
      ["selectionIndex"] = 100,
      ["spellId"] = 445029,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122494,
      ["entryId"] = 117482,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.arc_discharge",
      ["maxRanks"] = 1,
      ["name"] = "Arc Discharge",
      ["nodeId"] = 94885,
      ["selectionIndex"] = 100,
      ["spellId"] = 455096,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 119296,
      ["entryId"] = 114291,
      ["id"] = "enhancement.ascendance",
      ["maxRanks"] = 1,
      ["name"] = "Ascendance",
      ["nodeId"] = 92219,
      ["replacesSpellId"] = 384352,
      ["selectionIndex"] = 200,
      ["spellId"] = 114051,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106897,
      ["entryId"] = 101811,
      ["id"] = "enhancement.ashen_catalyst",
      ["maxRanks"] = 1,
      ["name"] = "Ashen Catalyst",
      ["nodeId"] = 80947,
      ["selectionIndex"] = 0,
      ["spellId"] = 390370,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122476,
      ["entryId"] = 117464,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.awakening_storms",
      ["maxRanks"] = 1,
      ["name"] = "Awakening Storms",
      ["nodeId"] = 94867,
      ["selectionIndex"] = 100,
      ["spellId"] = 455129,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 132665,
      ["entryId"] = 127856,
      ["id"] = "enhancement.chain_lightning",
      ["maxRanks"] = 1,
      ["name"] = "Chain Lightning",
      ["nodeId"] = 103583,
      ["selectionIndex"] = 100,
      ["spellId"] = 188443,
      ["tree"] = "class",
    },
    {
      ["definitionId"] = 140022,
      ["entryId"] = 135254,
      ["id"] = "enhancement.chaining_storms",
      ["maxRanks"] = 1,
      ["name"] = "Chaining Storms",
      ["nodeId"] = 109192,
      ["selectionIndex"] = 100,
      ["spellId"] = 334308,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 132693,
      ["entryId"] = 127884,
      ["id"] = "enhancement.cleanse_spirit",
      ["maxRanks"] = 1,
      ["name"] = "Cleanse Spirit",
      ["nodeId"] = 103608,
      ["selectionIndex"] = 100,
      ["spellId"] = 51886,
      ["tree"] = "class",
    },
    {
      ["definitionId"] = 122477,
      ["entryId"] = 117465,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.conductive_energy",
      ["maxRanks"] = 1,
      ["name"] = "Conductive Energy",
      ["nodeId"] = 94868,
      ["selectionIndex"] = 100,
      ["spellId"] = 455123,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106878,
      ["entryId"] = 101839,
      ["id"] = "enhancement.converging_storms",
      ["maxRanks"] = 1,
      ["name"] = "Converging Storms",
      ["nodeId"] = 80973,
      ["selectionIndex"] = 100,
      ["spellId"] = 384363,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106879,
      ["entryId"] = 101840,
      ["id"] = "enhancement.crash_lightning",
      ["maxRanks"] = 1,
      ["name"] = "Crash Lightning",
      ["nodeId"] = 80974,
      ["selectionIndex"] = 100,
      ["spellId"] = 187874,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106894,
      ["entryId"] = 101816,
      ["id"] = "enhancement.deeply_rooted_elements",
      ["maxRanks"] = 1,
      ["name"] = "Deeply Rooted Elements",
      ["nodeId"] = 92219,
      ["replacesSpellId"] = 384352,
      ["selectionIndex"] = 100,
      ["spellId"] = 378270,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140740,
      ["entryId"] = 135985,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.descending_skies",
      ["maxRanks"] = 1,
      ["name"] = "Descending Skies",
      ["nodeId"] = 109727,
      ["selectionIndex"] = 100,
      ["spellId"] = 1264688,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106859,
      ["entryId"] = 101824,
      ["id"] = "enhancement.doom_winds",
      ["maxRanks"] = 1,
      ["name"] = "Doom Winds",
      ["nodeId"] = 80959,
      ["selectionIndex"] = 100,
      ["spellId"] = 384352,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 130653,
      ["entryId"] = 125822,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.earthsurge",
      ["maxRanks"] = 1,
      ["name"] = "Earthsurge",
      ["nodeId"] = 94881,
      ["selectionIndex"] = 200,
      ["spellId"] = 455590,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 133033,
      ["entryId"] = 128226,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.electroshock",
      ["maxRanks"] = 1,
      ["name"] = "Electroshock",
      ["nodeId"] = 94863,
      ["selectionIndex"] = 200,
      ["spellId"] = 454022,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106893,
      ["entryId"] = 101815,
      ["id"] = "enhancement.elemental_assault",
      ["maxRanks"] = 1,
      ["name"] = "Elemental Assault",
      ["nodeId"] = 80951,
      ["selectionIndex"] = 100,
      ["spellId"] = 210853,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140738,
      ["entryId"] = 135983,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.elemental_attunement",
      ["maxRanks"] = 1,
      ["name"] = "Elemental Attunement",
      ["nodeId"] = 109725,
      ["selectionIndex"] = 100,
      ["spellId"] = 1263288,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106861,
      ["entryId"] = 101826,
      ["id"] = "enhancement.elemental_tempo",
      ["maxRanks"] = 1,
      ["name"] = "Elemental Tempo",
      ["nodeId"] = 80961,
      ["selectionIndex"] = 100,
      ["spellId"] = 1250364,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106868,
      ["entryId"] = 101818,
      ["id"] = "enhancement.elemental_weapons",
      ["maxRanks"] = 1,
      ["name"] = "Elemental Weapons",
      ["nodeId"] = 80953,
      ["selectionIndex"] = 100,
      ["spellId"] = 384355,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 133043,
      ["entryId"] = 128236,
      ["id"] = "enhancement.feral_spirit",
      ["maxRanks"] = 1,
      ["name"] = "Feral Spirit",
      ["nodeId"] = 109194,
      ["selectionIndex"] = 100,
      ["spellId"] = 469314,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140949,
      ["entryId"] = 136176,
      ["id"] = "enhancement.fire_nova",
      ["maxRanks"] = 1,
      ["name"] = "Fire Nova",
      ["nodeId"] = 109909,
      ["selectionIndex"] = 100,
      ["spellId"] = 1260666,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106864,
      ["entryId"] = 101805,
      ["id"] = "enhancement.flametongue_weapon",
      ["maxRanks"] = 1,
      ["name"] = "Flametongue Weapon",
      ["nodeId"] = 80942,
      ["selectionIndex"] = 100,
      ["spellId"] = 318038,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106872,
      ["entryId"] = 101799,
      ["id"] = "enhancement.flurry",
      ["maxRanks"] = 1,
      ["name"] = "Flurry",
      ["nodeId"] = 103642,
      ["selectionIndex"] = 100,
      ["spellId"] = 382888,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106888,
      ["entryId"] = 101834,
      ["id"] = "enhancement.forceful_winds",
      ["maxRanks"] = 1,
      ["name"] = "Forceful Winds",
      ["nodeId"] = 80969,
      ["selectionIndex"] = 100,
      ["spellId"] = 262647,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140473,
      ["entryId"] = 135718,
      ["id"] = "enhancement.frost_shock",
      ["maxRanks"] = 1,
      ["name"] = "Frost Shock",
      ["nodeId"] = 109492,
      ["selectionIndex"] = 100,
      ["spellId"] = 196840,
      ["tree"] = "class",
    },
    {
      ["definitionId"] = 106898,
      ["entryId"] = 101809,
      ["id"] = "enhancement.hot_hand",
      ["maxRanks"] = 2,
      ["name"] = "Hot Hand",
      ["nodeId"] = 80945,
      ["selectionIndex"] = 100,
      ["spellId"] = 201900,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122480,
      ["entryId"] = 117468,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.imbuement_mastery",
      ["maxRanks"] = 1,
      ["name"] = "Imbuement Mastery",
      ["nodeId"] = 94871,
      ["selectionIndex"] = 100,
      ["spellId"] = 445028,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106896,
      ["entryId"] = 101812,
      ["id"] = "enhancement.lashing_flames",
      ["maxRanks"] = 1,
      ["name"] = "Lashing Flames",
      ["nodeId"] = 80948,
      ["selectionIndex"] = 100,
      ["spellId"] = 334046,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140349,
      ["entryId"] = 135593,
      ["id"] = "enhancement.lava_lash",
      ["maxRanks"] = 1,
      ["name"] = "Lava Lash",
      ["nodeId"] = 109389,
      ["selectionIndex"] = 100,
      ["spellId"] = 60103,
      ["tree"] = "class",
    },
    {
      ["definitionId"] = 122472,
      ["entryId"] = 117460,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.lightning_conduit",
      ["maxRanks"] = 1,
      ["name"] = "Lightning Conduit",
      ["nodeId"] = 94863,
      ["selectionIndex"] = 100,
      ["spellId"] = 467778,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 140023,
      ["entryId"] = 135255,
      ["id"] = "enhancement.lightning_strikes",
      ["maxRanks"] = 1,
      ["name"] = "Lightning Strikes",
      ["nodeId"] = 109193,
      ["selectionIndex"] = 100,
      ["spellId"] = 384450,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122491,
      ["entryId"] = 117479,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.lively_totems",
      ["maxRanks"] = 1,
      ["name"] = "Lively Totems",
      ["nodeId"] = 94882,
      ["selectionIndex"] = 100,
      ["spellId"] = 445034,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106862,
      ["entryId"] = 101804,
      ["id"] = "enhancement.maelstrom_weapon",
      ["maxRanks"] = 1,
      ["name"] = "Maelstrom Weapon",
      ["nodeId"] = 80941,
      ["selectionIndex"] = 100,
      ["spellId"] = 187880,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106863,
      ["entryId"] = 101806,
      ["id"] = "enhancement.molten_assault",
      ["maxRanks"] = 1,
      ["name"] = "Molten Assault",
      ["nodeId"] = 80943,
      ["selectionIndex"] = 100,
      ["spellId"] = 334033,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140741,
      ["entryId"] = 135986,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.natural_gift",
      ["maxRanks"] = 1,
      ["name"] = "Natural Gift",
      ["nodeId"] = 109728,
      ["selectionIndex"] = 100,
      ["spellId"] = 1264691,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122489,
      ["entryId"] = 117477,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.natures_protection",
      ["maxRanks"] = 1,
      ["name"] = "Nature's Protection",
      ["nodeId"] = 94880,
      ["selectionIndex"] = 100,
      ["spellId"] = 454027,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106900,
      ["entryId"] = 101808,
      ["id"] = "enhancement.overcharge",
      ["maxRanks"] = 1,
      ["name"] = "Overcharge",
      ["nodeId"] = 80944,
      ["selectionIndex"] = 100,
      ["spellId"] = 1251026,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106871,
      ["entryId"] = 101802,
      ["id"] = "enhancement.overflowing_maelstrom",
      ["maxRanks"] = 1,
      ["name"] = "Overflowing Maelstrom",
      ["nodeId"] = 80939,
      ["selectionIndex"] = 0,
      ["spellId"] = 384143,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122468,
      ["entryId"] = 117456,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.oversized_totems",
      ["maxRanks"] = 1,
      ["name"] = "Oversized Totems",
      ["nodeId"] = 94859,
      ["selectionIndex"] = 100,
      ["spellId"] = 445026,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 130654,
      ["entryId"] = 125823,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.oversurge",
      ["maxRanks"] = 1,
      ["name"] = "Oversurge",
      ["nodeId"] = 94874,
      ["selectionIndex"] = 200,
      ["spellId"] = 445030,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 140737,
      ["entryId"] = 135982,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.primal_catalyst",
      ["maxRanks"] = 1,
      ["name"] = "Primal Catalyst",
      ["nodeId"] = 109724,
      ["selectionIndex"] = 100,
      ["spellId"] = 1260874,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106883,
      ["entryId"] = 101828,
      ["id"] = "enhancement.primordial_storm",
      ["maxRanks"] = 1,
      ["name"] = "Primordial Storm",
      ["nodeId"] = 80963,
      ["selectionIndex"] = 100,
      ["spellId"] = 1218047,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122475,
      ["entryId"] = 117463,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.pulse_capacitor",
      ["maxRanks"] = 1,
      ["name"] = "Pulse Capacitor",
      ["nodeId"] = 94866,
      ["selectionIndex"] = 100,
      ["spellId"] = 445032,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106880,
      ["entryId"] = 101801,
      ["id"] = "enhancement.raging_maelstrom",
      ["maxRanks"] = 1,
      ["name"] = "Raging Maelstrom",
      ["nodeId"] = 80938,
      ["selectionIndex"] = 0,
      ["spellId"] = 384149,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106860,
      ["entryId"] = 101827,
      ["id"] = "enhancement.ride_the_lightning",
      ["maxRanks"] = 1,
      ["name"] = "Ride the Lightning",
      ["nodeId"] = 80962,
      ["selectionIndex"] = 100,
      ["spellId"] = 289874,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122498,
      ["entryId"] = 117486,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.rolling_thunder",
      ["maxRanks"] = 1,
      ["name"] = "Rolling Thunder",
      ["nodeId"] = 94889,
      ["selectionIndex"] = 100,
      ["spellId"] = 454026,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122481,
      ["entryId"] = 117469,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.splitstream",
      ["maxRanks"] = 1,
      ["name"] = "Splitstream",
      ["nodeId"] = 94872,
      ["selectionIndex"] = 100,
      ["spellId"] = 445035,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106881,
      ["entryId"] = 101814,
      ["id"] = "enhancement.static_accumulation",
      ["maxRanks"] = 2,
      ["name"] = "Static Accumulation",
      ["nodeId"] = 80950,
      ["selectionIndex"] = 100,
      ["spellId"] = 384411,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122482,
      ["entryId"] = 117470,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.storm_swell",
      ["maxRanks"] = 1,
      ["name"] = "Storm Swell",
      ["nodeId"] = 94873,
      ["selectionIndex"] = 100,
      ["spellId"] = 455088,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 141732,
      ["entryId"] = 136969,
      ["id"] = "enhancement.storm_unleashed_crash_lightning",
      ["maxRanks"] = 1,
      ["name"] = "Storm Unleashed",
      ["nodeId"] = 110401,
      ["selectionIndex"] = 300,
      ["spellId"] = 1252373,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 141733,
      ["entryId"] = 136970,
      ["id"] = "enhancement.storm_unleashed_maelstrom",
      ["maxRanks"] = 2,
      ["name"] = "Storm Unleashed",
      ["nodeId"] = 110401,
      ["selectionIndex"] = 200,
      ["spellId"] = 1262761,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 141734,
      ["entryId"] = 136971,
      ["id"] = "enhancement.storm_unleashed_reset",
      ["maxRanks"] = 1,
      ["name"] = "Storm Unleashed",
      ["nodeId"] = 110401,
      ["selectionIndex"] = 100,
      ["spellId"] = 1262713,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140021,
      ["entryId"] = 135253,
      ["id"] = "enhancement.stormbind",
      ["maxRanks"] = 1,
      ["name"] = "Stormbind",
      ["nodeId"] = 109191,
      ["selectionIndex"] = 100,
      ["spellId"] = 1251069,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106877,
      ["entryId"] = 101825,
      ["id"] = "enhancement.stormblast",
      ["maxRanks"] = 1,
      ["name"] = "Stormblast",
      ["nodeId"] = 80960,
      ["selectionIndex"] = 100,
      ["spellId"] = 319930,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122502,
      ["entryId"] = 117490,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.stormcaller",
      ["maxRanks"] = 1,
      ["name"] = "Stormcaller",
      ["nodeId"] = 94893,
      ["selectionIndex"] = 100,
      ["spellId"] = 454021,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 133077,
      ["entryId"] = 128270,
      ["id"] = "enhancement.stormflurry",
      ["maxRanks"] = 1,
      ["name"] = "Stormflurry",
      ["nodeId"] = 103871,
      ["selectionIndex"] = 100,
      ["spellId"] = 344357,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 107009,
      ["entryId"] = 101832,
      ["id"] = "enhancement.storms_wrath",
      ["maxRanks"] = 1,
      ["name"] = "Storm's Wrath",
      ["nodeId"] = 80967,
      ["selectionIndex"] = 100,
      ["spellId"] = 392352,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140742,
      ["entryId"] = 135987,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.stormwell",
      ["maxRanks"] = 1,
      ["name"] = "Stormwell",
      ["nodeId"] = 109729,
      ["selectionIndex"] = 100,
      ["spellId"] = 1264762,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106874,
      ["entryId"] = 101841,
      ["id"] = "enhancement.sundering",
      ["maxRanks"] = 1,
      ["name"] = "Sundering",
      ["nodeId"] = 80975,
      ["selectionIndex"] = 100,
      ["spellId"] = 197214,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 133032,
      ["entryId"] = 128225,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.supercharge",
      ["maxRanks"] = 1,
      ["name"] = "Supercharge",
      ["nodeId"] = 94873,
      ["selectionIndex"] = 200,
      ["spellId"] = 455110,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 130655,
      ["entryId"] = 125824,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.supportive_imbuements",
      ["maxRanks"] = 1,
      ["name"] = "Supportive Imbuements",
      ["nodeId"] = 94866,
      ["selectionIndex"] = 200,
      ["spellId"] = 445033,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 130449,
      ["entryId"] = 125617,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.surging_currents",
      ["maxRanks"] = 1,
      ["name"] = "Surging Currents",
      ["nodeId"] = 94880,
      ["selectionIndex"] = 200,
      ["spellId"] = 454372,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106884,
      ["entryId"] = 101829,
      ["id"] = "enhancement.surging_elements",
      ["maxRanks"] = 1,
      ["name"] = "Surging Elements",
      ["nodeId"] = 80964,
      ["selectionIndex"] = 100,
      ["spellId"] = 382042,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122486,
      ["entryId"] = 117474,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.surging_totem",
      ["maxRanks"] = 1,
      ["name"] = "Surging Totem",
      ["nodeId"] = 94877,
      ["selectionIndex"] = 100,
      ["spellId"] = 455630,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 130656,
      ["entryId"] = 125825,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.swift_recall",
      ["maxRanks"] = 1,
      ["name"] = "Swift Recall",
      ["nodeId"] = 94859,
      ["selectionIndex"] = 200,
      ["spellId"] = 445027,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122501,
      ["entryId"] = 117489,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.tempest",
      ["maxRanks"] = 1,
      ["name"] = "Tempest",
      ["nodeId"] = 94892,
      ["selectionIndex"] = 100,
      ["spellId"] = 454009,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106882,
      ["entryId"] = 101813,
      ["id"] = "enhancement.thorims_invocation",
      ["maxRanks"] = 1,
      ["name"] = "Thorim's Invocation",
      ["nodeId"] = 80949,
      ["selectionIndex"] = 100,
      ["spellId"] = 384444,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 140020,
      ["entryId"] = 135252,
      ["id"] = "enhancement.thunder_capacitor",
      ["maxRanks"] = 1,
      ["name"] = "Thunder Capacitor",
      ["nodeId"] = 109190,
      ["selectionIndex"] = 100,
      ["spellId"] = 1262635,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122490,
      ["entryId"] = 117478,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.totemic_coordination",
      ["maxRanks"] = 1,
      ["name"] = "Totemic Coordination",
      ["nodeId"] = 94881,
      ["selectionIndex"] = 100,
      ["spellId"] = 445036,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 140739,
      ["entryId"] = 135984,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.totemic_momentum",
      ["maxRanks"] = 1,
      ["name"] = "Totemic Momentum",
      ["nodeId"] = 109726,
      ["selectionIndex"] = 100,
      ["spellId"] = 1260644,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122499,
      ["entryId"] = 117487,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.totemic_rebound",
      ["maxRanks"] = 1,
      ["name"] = "Totemic Rebound",
      ["nodeId"] = 94890,
      ["selectionIndex"] = 100,
      ["spellId"] = 445025,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122495,
      ["entryId"] = 117483,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.unlimited_power",
      ["maxRanks"] = 1,
      ["name"] = "Unlimited Power",
      ["nodeId"] = 94886,
      ["selectionIndex"] = 100,
      ["spellId"] = 454391,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106887,
      ["entryId"] = 101833,
      ["id"] = "enhancement.unruly_winds",
      ["maxRanks"] = 1,
      ["name"] = "Unruly Winds",
      ["nodeId"] = 80968,
      ["selectionIndex"] = 100,
      ["spellId"] = 390288,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 106869,
      ["entryId"] = 101819,
      ["id"] = "enhancement.voltaic_blaze",
      ["maxRanks"] = 1,
      ["name"] = "Voltaic Blaze",
      ["nodeId"] = 80954,
      ["replacesSpellId"] = 470411,
      ["selectionIndex"] = 100,
      ["spellId"] = 470057,
      ["tree"] = "spec",
    },
    {
      ["definitionId"] = 122479,
      ["entryId"] = 117467,
      ["heroTreeId"] = "enhancement.stormbringer",
      ["id"] = "enhancement.voltaic_surge",
      ["maxRanks"] = 1,
      ["name"] = "Voltaic Surge",
      ["nodeId"] = 94870,
      ["selectionIndex"] = 100,
      ["spellId"] = 454919,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122488,
      ["entryId"] = 117476,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.whirling_elements",
      ["maxRanks"] = 1,
      ["name"] = "Whirling Elements",
      ["nodeId"] = 94879,
      ["selectionIndex"] = 100,
      ["spellId"] = 445024,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 122500,
      ["entryId"] = 117488,
      ["heroTreeId"] = "enhancement.totemic",
      ["id"] = "enhancement.wind_barrier",
      ["maxRanks"] = 1,
      ["name"] = "Wind Barrier",
      ["nodeId"] = 94891,
      ["selectionIndex"] = 100,
      ["spellId"] = 445031,
      ["tree"] = "hero",
    },
    {
      ["definitionId"] = 106876,
      ["entryId"] = 101823,
      ["id"] = "enhancement.windfury_weapon",
      ["maxRanks"] = 1,
      ["name"] = "Windfury Weapon",
      ["nodeId"] = 80958,
      ["selectionIndex"] = 100,
      ["spellId"] = 33757,
      ["tree"] = "spec",
    },
  },
  ["version"] = "12.1.0-1",
}

Spynon.Classes = Spynon.Classes or {}
Spynon.Classes.Shaman = Spynon.Classes.Shaman or {}
Spynon.Classes.Shaman.Enhancement = Spynon.Classes.Shaman.Enhancement or {}
Spynon.Classes.Shaman.Enhancement.Catalog = Catalog
