-- Generated by Spynon's Rotation compiler; do not edit.
return {
  ["entrypoint"] = "single_sb",
  ["excludedRules"] = {},
  ["lists"] = {
    {
      ["id"] = "aoe",
      ["rules"] = {
        {
          ["action"] = "enhancement.voltaic_blaze",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_voltaic_blaze_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 10,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.surging_totem",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.flame_shock",
                "remains",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 0,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "eq",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.flame_shock",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_flame_shock_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 20,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.flame_shock",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
          },
        },
        {
          ["action"] = "enhancement.surging_totem",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_surging_totem_1",
          ["priority"] = 30,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.doom_winds",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_doom_winds_1",
          ["priority"] = 40,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.lava_lash",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_lava_lash_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 50,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.splitstream",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.hot_hand",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.tempest",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_tempest_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 60,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 10,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.ascendance",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
            {
              ["count"] = 2,
              ["op"] = "ANY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.primordial_storm",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_primordial_storm_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 70,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 10,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
          },
        },
        {
          ["action"] = "enhancement.crash_lightning",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_crash_lightning_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 80,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.ascendance",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ANY",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.splitstream",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.hot_hand",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 4,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.windstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_windstrike_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 90,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.splitstream",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.hot_hand",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 3,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_stormstrike_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 100,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.splitstream",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.hot_hand",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 4,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.crash_lightning",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_crash_lightning_2",
          ["priority"] = 110,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.windstrike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_windstrike_2",
          ["priority"] = 120,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_stormstrike_2",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 130,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.sundering",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_sundering_1",
          ["priority"] = 140,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.feral_spirit",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
          },
        },
        {
          ["action"] = "enhancement.voltaic_blaze",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_voltaic_blaze_2",
          ["priority"] = 150,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.windstrike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_windstrike_3",
          ["priority"] = 160,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.sundering",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_sundering_2",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 170,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "cooldowns",
                "enhancement.surging_totem",
                "remains",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 25,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gt",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_stormstrike_3",
          ["priority"] = 180,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.surging_totem",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
          },
        },
        {
          ["action"] = "enhancement.lava_lash",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_lava_lash_2",
          ["priority"] = 190,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_stormstrike_4",
          ["priority"] = 200,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.chain_lightning",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.aoe_chain_lightning_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 210,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
          },
        },
        {
          ["action"] = "enhancement.flame_shock",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.aoe_flame_shock_2",
          ["priority"] = 220,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
      },
    },
    {
      ["id"] = "precombat",
      ["rules"] = {
        {
          ["action"] = "enhancement.windfury_weapon",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.precombat_windfury_weapon_1",
          ["priority"] = 10,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.flametongue_weapon",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.precombat_flametongue_weapon_1",
          ["priority"] = 20,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.lightning_shield",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.precombat_lightning_shield_1",
          ["priority"] = 30,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
      },
    },
    {
      ["id"] = "single_sb",
      ["rules"] = {
        {
          ["action"] = "enhancement.primordial_storm",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_primordial_storm_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 10,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 9,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.primordial_storm",
                "remains",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 4,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "lte",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
            {
              ["count"] = 2,
              ["op"] = "ANY",
            },
          },
        },
        {
          ["action"] = "enhancement.voltaic_blaze",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_voltaic_blaze_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 20,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.flame_shock",
                "remains",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 0,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "eq",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "combat",
                "elapsed_seconds",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "lt",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.flame_shock",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_flame_shock_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 30,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.flame_shock",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
          },
        },
        {
          ["action"] = "enhancement.lava_lash",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_lava_lash_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 40,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.lashing_flames",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "combat",
                "elapsed_seconds",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "lt",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_stormstrike_1",
          ["priority"] = 50,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "combat",
                "elapsed_seconds",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 1,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "lt",
            },
          },
        },
        {
          ["action"] = "enhancement.sundering",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_sundering_1",
          ["priority"] = 60,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.surging_elements",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.feral_spirit",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ANY",
            },
          },
        },
        {
          ["action"] = "enhancement.doom_winds",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_doom_winds_1",
          ["priority"] = 70,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.windstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_windstrike_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 80,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 0,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gt",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.ascendance",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_ascendance_1",
          ["priority"] = 90,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_stormstrike_2",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 100,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.crash_lightning",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_crash_lightning_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 110,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.tempest",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_tempest_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 120,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 10,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "eq",
            },
          },
        },
        {
          ["action"] = "enhancement.lightning_bolt",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_lightning_bolt_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 130,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 10,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "eq",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_stormstrike_3",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 140,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "cooldowns",
                "enhancement.stormstrike",
                "charges_fractional",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 1.8,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
          },
        },
        {
          ["action"] = "enhancement.lava_lash",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_lava_lash_2",
          ["priority"] = 150,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.lashing_flames",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_stormstrike_4",
          ["priority"] = 160,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.voltaic_blaze",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_voltaic_blaze_2",
          ["priority"] = 170,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.sundering",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_sundering_2",
          ["priority"] = 180,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.lava_lash",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_lava_lash_3",
          ["priority"] = 190,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.lightning_bolt",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_lightning_bolt_2",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 200,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 8,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
          },
        },
        {
          ["action"] = "enhancement.crash_lightning",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_crash_lightning_2",
          ["priority"] = 210,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.lightning_bolt",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_sb_lightning_bolt_3",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 220,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
          },
        },
        {
          ["action"] = "enhancement.flame_shock",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_sb_flame_shock_2",
          ["priority"] = 230,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
      },
    },
    {
      ["id"] = "single_totemic",
      ["rules"] = {
        {
          ["action"] = "enhancement.voltaic_blaze",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_voltaic_blaze_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 10,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.flame_shock",
                "remains",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 0,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "eq",
            },
          },
        },
        {
          ["action"] = "enhancement.flame_shock",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_flame_shock_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 20,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.flame_shock",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
          },
        },
        {
          ["action"] = "enhancement.surging_totem",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_totemic_surging_totem_1",
          ["priority"] = 30,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.doom_winds",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_totemic_doom_winds_1",
          ["priority"] = 40,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.primordial_storm",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_primordial_storm_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 50,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 10,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.primordial_storm",
                "remains",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 3.5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "lt",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
            {
              ["count"] = 2,
              ["op"] = "ANY",
            },
          },
        },
        {
          ["action"] = "enhancement.windstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_windstrike_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 60,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.ascendance",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.crash_lightning",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_crash_lightning_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 70,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.ascendance",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ANY",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_stormstrike_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 80,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "talents",
                "enhancement.thorims_invocation",
                "enabled",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.doom_winds",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "enhancement.crash_lightning",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_crash_lightning_2",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 90,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "auras",
                "enhancement.crash_lightning",
                "active",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["op"] = "NOT",
            },
          },
        },
        {
          ["action"] = "enhancement.lava_lash",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_totemic_lava_lash_1",
          ["priority"] = 100,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.sundering",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_sundering_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 110,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "cooldowns",
                "enhancement.surging_totem",
                "remains",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 25,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gt",
            },
          },
        },
        {
          ["action"] = "enhancement.stormstrike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_totemic_stormstrike_2",
          ["priority"] = 120,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.voltaic_blaze",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_totemic_voltaic_blaze_2",
          ["priority"] = 130,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.crash_lightning",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_totemic_crash_lightning_3",
          ["priority"] = 140,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
        {
          ["action"] = "enhancement.lightning_bolt",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "enhancement.single_totemic_lightning_bolt_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 150,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "enhancement.maelstrom_weapon",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 5,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
          },
        },
        {
          ["action"] = "enhancement.flame_shock",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "enhancement.single_totemic_flame_shock_2",
          ["priority"] = 160,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
      },
    },
  },
  ["schemaVersion"] = 1,
  ["source"] = {
    ["dslSchemaVersion"] = 1,
    ["id"] = "enhancement.simc_baseline",
    ["sha256"] = "036BEE377D6C5B492B3EF1F670F9D1F6DE6CCC4A098A972C29B3F578669C0BA0",
    ["version"] = "12.1.0-1",
  },
}
