local passed, total, failures = 0, 0, {}
local function eq(a,b) if a ~= b then error("expected " .. tostring(b) .. ", got " .. tostring(a)) end end
local function test(name, fn)
  total = total + 1; local ok, err = pcall(fn)
  if ok then passed = passed + 1 else failures[#failures+1] = name .. ": " .. tostring(err) end
  print((ok and "[PASS] " or "[FAIL] ") .. name)
end
local factory = assert(loadfile("tests/fixtures/specs/frame_environment.lua"))()
CreateFrame = factory(); local ns = {}
for line in io.lines("addon/SpynonRotation.toc") do
  local file = line:match("^([^#].*%.lua)%s*$")
  if file then assert(loadfile("addon/" .. file))("SpynonRotation", ns) end
end
local guid = "Player-999-ABCDEF"
local function fixture(saved)
  local createFrame, objects = factory()
  local data = { combat = false, guid = guid, specId = 9101 }
  local env = { SpynonRotationDB = saved, issecretvalue = function() return false end,
    UnitAffectingCombat = function() return data.combat end, UnitGUID = function() return data.guid end,
    GetTime = function() return 100 end, UIParent = {}, C_SpecializationInfo = {
      GetSpecialization = function() return 1 end, GetSpecializationInfo = function() return data.specId end } }
  local compat, model = ns.CompatFactory.Create(env), ns.SettingsFactory.Create()
  ns.Settings = model
  local profiles = ns.ProfileControllerFactory.Create(compat, createFrame, model); profiles:Start()
  local live = { Start = function() end, Stop = function() end }
  local harness = ns.InGameHarnessFactory.Create(compat, {GetSelection = function() return nil end},
    {GetRecommendations = function() return {} end}, live, ns.Specs, createFrame)
  harness:Start()
  local config = ns.ConfigControllerFactory.Create(compat, createFrame, model, harness, profiles)
  config:Start(); config:Edit()
  return config:GetHistory(), model, profiles, env.SpynonRotationDB, data, config, objects
end
local function sliderOf(objects)
  for _, object in ipairs(objects) do if object.kind == "Slider" then return object end end
  error("slider missing")
end
test("history begins empty and undo/redo are distinct unavailable operations", function()
  local history = fixture()
  eq(history:GetStatus().undo, 0); eq(history:GetStatus().redo, 0)
  eq(history:Undo(), false); eq(history:Redo(), false)
end)
test("undo restores absence of override and redo reapplies only the original change", function()
  local history, model, _, saved = fixture()
  eq(history:Execute("count", 2), true); eq(saved.profiles.global.count, 2)
  eq(history:Undo(), true); eq(model:Get().count, 4); eq(saved.profiles.global.count, nil)
  eq(history:GetStatus().redo, 1); eq(history:Redo(), true); eq(saved.profiles.global.count, 2)
end)
test("inherited preferences remain inherited after undo rather than copied into a spec", function()
  local history, model, profiles, saved = fixture()
  model:Set("scale", 0.75); profiles:Select("spec")
  history:Execute("scale", 1.25); history:Undo()
  eq(model:Get().scale, 0.75); eq(saved.profiles.characters[guid].specs["9101"].scale, nil)
  eq(saved.profiles.global.scale, 0.75)
end)
test("a new action after undo discards the abandoned redo branch", function()
  local history, model = fixture()
  history:Execute("count", 2); history:Execute("scale", 0.75); history:Undo()
  history:Execute("keys", "off"); eq(history:GetStatus().redo, 0)
  eq(history:Redo(), false); eq(model:Get().scale, 1); eq(model:Get().keys, "off")
end)
test("repeating the same explicit override does not add another history entry", function()
  local history = fixture()
  history:Execute("count", 2); history:Execute("count", 2); eq(history:GetStatus().undo, 1)
end)
test("history is bounded to fifty actions and rejects malformed edits", function()
  local history, _, _, saved = fixture()
  for i = 1, 80 do history:Execute("count", i%4+1) end
  eq(history:GetStatus().undo, 50)
  eq(history:Execute("unknown", 1), false); eq(history:Execute("count", 5), false)
  eq(saved.profiles.global.count, 1); eq(history:GetStatus().undo, 50)
end)
test("a hundred preview updates remain unpersisted until one transaction commits", function()
  local history, model, _, saved = fixture()
  history:Begin("mainScale")
  for index = 1, 100 do history:Preview("mainScale", index%2 == 0 and 1.15 or 0.85) end
  eq(model:Get().mainScale, 1.15); eq(saved.profiles.global.mainScale, nil)
  eq(history:GetStatus().undo, 0); eq(history:GetStatus().active, true)
  eq(history:Commit(), true); eq(history:GetStatus().undo, 1); eq(saved.profiles.global.mainScale, 1.15)
  history:Undo(); eq(model:Get().mainScale, 1); eq(saved.profiles.global.mainScale, nil)
end)
test("cancel restores the visible state without writing or creating undo entries", function()
  local history, model, _, saved = fixture()
  history:Begin("mainScale"); history:Preview("mainScale", 0.85); history:Cancel()
  eq(model:Get().mainScale, 1); eq(saved.profiles.global.mainScale, nil); eq(history:GetStatus().undo, 0)
  eq(history:Commit(), false)
end)
test("a drag returning to its starting point is a no-op with no new override", function()
  local history, _, _, saved = fixture()
  history:Begin("mainScale"); history:Preview("mainScale", 0.85); history:Preview("mainScale", 1)
  history:Commit(); eq(history:GetStatus().undo, 0); eq(saved.profiles.global.mainScale, nil)
end)
test("mouse event order still records a whole slider drag as one action", function()
  for _, valueFirst in ipairs({false,true}) do
    local history, model, _, saved, _, config, objects = fixture()
    config:GetPanel():SelectElement("current")
    local slider = sliderOf(objects)
    if valueFirst then slider:SetValue(1) end
    slider.scripts.OnMouseDown(slider, "LeftButton")
    slider:SetValue(1); slider:SetValue(2); slider:SetValue(3)
    eq(saved.profiles.global.mainScale, nil); eq(model:Get().mainScale, 1.15)
    slider.scripts.OnMouseUp(slider, "LeftButton")
    eq(history:GetStatus().undo, 1); eq(saved.profiles.global.mainScale, 1.15)
  end
end)
test("navigation and closing cancel preview and leave saved preferences unchanged", function()
  local history, model, _, saved, _, config, objects = fixture()
  config:GetPanel():SelectElement("current")
  sliderOf(objects):SetValue(1); config:GetPanel():Select(nil)
  eq(model:Get().mainScale, 1); eq(history:GetStatus().active, false)
  config:GetPanel():SelectElement("current"); sliderOf(objects):SetValue(3); config:Close()
  eq(model:Get().mainScale, 1); eq(saved.profiles.global.mainScale, nil)
end)
test("combat during a preview cancels instead of persisting an intermediate value", function()
  local history, model, _, saved, data, config = fixture()
  history:Begin("mainScale"); history:Preview("mainScale", 1.15)
  data.combat = true; config:Close()
  eq(saved.profiles.global.mainScale, nil); eq(model:Get().mainScale, 1)
  eq(history:GetStatus().active, false); eq(history:Undo(), false)
end)
test("scope selection invalidates history and cannot apply an old undo to a new scope", function()
  local history, model, profiles, saved = fixture()
  history:Execute("count", 2); profiles:Select("character")
  eq(history:GetStatus().undo, 0); eq(history:Undo(), false)
  eq(model:Get().count, 2); eq(next(saved.profiles.characters[guid].values), nil)
end)
test("profile copy and reset are separate guarded operations that invalidate history", function()
  local history, model, profiles, saved = fixture()
  model:Set("count", 2); profiles:Select("character"); history:Execute("count", 1)
  profiles:Copy("global"); eq(model:Get().count, 2); eq(history:GetStatus().undo, 0)
  history:Execute("scale", 0.75); profiles:Reset()
  eq(history:GetStatus().undo, 0); eq(model:Get().scale, 1); eq(saved.profiles.global.count, 2)
end)
test("specialization changes cancel preview and preserve both specialization profiles", function()
  local history, model, profiles, saved, data = fixture()
  profiles:Select("spec"); history:Execute("count", 2)
  history:Begin("mainScale"); history:Preview("mainScale", 1.15)
  data.specId = 9102; profiles:Refresh()
  eq(history:GetStatus().active, false); eq(history:GetStatus().undo, 0)
  eq(model:Get().mainScale, 1); eq(saved.profiles.characters[guid].specs["9101"].count, 2)
  eq(saved.profiles.characters[guid].specs["9102"], nil)
end)
test("identity drift before commit fails closed even without a prior specialization event", function()
  local history, model, profiles, saved, data = fixture(); profiles:Select("spec")
  history:Begin("mainScale"); history:Preview("mainScale", 1.15)
  data.specId = 9102; eq(history:Commit(), false)
  eq(model:Get().mainScale, 1); eq(next(saved.profiles.characters[guid].specs), nil)
end)
test("external settings edits invalidate history rather than overwritten by a stale undo", function()
  local history, model = fixture()
  history:Execute("count", 2); model:Set("count", 3)
  eq(history:GetStatus().undo, 0); eq(history:Undo(), false); eq(model:Get().count, 3)
end)
test("unexpected direct storage changes are detected by the expected snapshot guard", function()
  local history, model, _, saved = fixture()
  history:Execute("count", 2); saved.profiles.global.count = 3
  eq(history:Undo(), false); eq(saved.profiles.global.count, 3); eq(model:Get().count, 3)
end)
test("undo preserves unknown extensions and unrelated malformed preferences", function()
  local history, _, _, saved = fixture({profiles={schemaVersion=1,global={count=99,extension={kept=true}},characters={}}})
  history:Execute("scale", 0.75); history:Undo()
  eq(saved.profiles.global.count, 99); eq(saved.profiles.global.extension.kept, true)
end)
test("multi-field apply validates the entire patch before changing any stored field", function()
  local _, _, profiles, saved = fixture(); local before = profiles:Capture()
  eq(profiles:Apply(before, { count = 2, scale = 999 }), false)
  eq(saved.profiles.global.count, nil); eq(saved.profiles.global.scale, nil)
  eq(profiles:Apply(before, { count = 2, scale = 0.75 }), true)
  eq(saved.profiles.global.count, 2); eq(saved.profiles.global.scale, 0.75)
end)
test("reload restores preferences but not ephemeral history", function()
  local history, _, _, saved = fixture(); history:Execute("count", 2)
  local restored, model = fixture(saved)
  eq(model:Get().count, 2); eq(restored:GetStatus().undo, 0); eq(restored:GetStatus().redo, 0)
end)
test("readonly profiles cannot leave a misleading slider value or visual preview", function()
  local history, model, _, _, _, config, objects = fixture({profiles={schemaVersion=2}})
  config:GetPanel():SelectElement("current")
  local slider = sliderOf(objects); slider:SetValue(3)
  eq(slider.value, 2); eq(model:Get().mainScale, 1); eq(history:GetStatus().active, false)
end)
test("history snapshots are isolated from both storage and adapter caller mutation", function()
  local history, _, profiles, saved = fixture()
  history:Execute("count", 2)
  local snapshot = profiles:Capture(); snapshot.values.count = 99
  eq(saved.profiles.global.count, 2); history:Undo(); history:Redo(); eq(saved.profiles.global.count, 2)
end)
print(string.format("Transactional history: %d/%d passed", passed, total))
for _, failure in ipairs(failures) do print(failure) end
if passed ~= total then os.exit(1) end
