-- Generated by Spynon's Rotation compiler; do not edit.
return {
  ["entrypoint"] = "default",
  ["excludedRules"] = {
    {
      ["action"] = "neutral.execute",
      ["list"] = "default",
      ["reason"] = "SIM_ONLY",
      ["rule"] = "neutral.default_execute_1",
    },
  },
  ["lists"] = {
    {
      ["id"] = "default",
      ["rules"] = {
        {
          ["action"] = "neutral.strike",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "neutral.default_strike_1",
          ["priority"] = 10,
          ["program"] = {
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "cooldowns",
                "neutral.strike",
                "ready",
              },
            },
            {
              ["op"] = "TRUTHY",
            },
            {
              ["capability"] = "ADDON_AVAILABLE",
              ["op"] = "READ_STATE",
              ["path"] = {
                "resources",
                "neutral_energy",
                "current",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 50,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
            {
              ["count"] = 2,
              ["op"] = "ALL",
            },
          },
        },
        {
          ["action"] = "neutral.cleave",
          ["capability"] = "CONDITIONALLY_SECRET",
          ["id"] = "neutral.default_cleave_1",
          ["onUnavailable"] = "skip_rule",
          ["priority"] = 20,
          ["program"] = {
            {
              ["capability"] = "CONDITIONALLY_SECRET",
              ["op"] = "READ_STATE",
              ["path"] = {
                "target",
                "estimated_count",
              },
            },
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = 2,
            },
            {
              ["op"] = "COMPARE",
              ["operator"] = "gte",
            },
          },
        },
      },
    },
    {
      ["id"] = "maintenance",
      ["rules"] = {
        {
          ["action"] = "neutral.maintenance",
          ["capability"] = "ADDON_AVAILABLE",
          ["id"] = "neutral.maintenance_maintenance_1",
          ["priority"] = 10,
          ["program"] = {
            {
              ["op"] = "PUSH_LITERAL",
              ["value"] = true,
            },
          },
        },
      },
    },
  },
  ["schemaVersion"] = 1,
  ["source"] = {
    ["dslSchemaVersion"] = 1,
    ["id"] = "neutral.compiler_fixture",
    ["sha256"] = "0B04C5D3EDB81F7E078C430E657598437D6476C0BFB4B394F88016088FE92E1D",
    ["version"] = "1.0.0",
  },
}
